<?php
// This is just a demo. Code is way to ugly for use. 
require_once("lib/config.php");
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="no-NB">
    <head profile="http://gmpg.org/xfn/11">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="keywords" content="Spotify Metadata API, Mikael Brevik, PHP Lib, Spotify" />
        <meta name="description" content="MetaTune examples" />
        <title>MetaTune - Demo</title>
        <link type="text/css" rel="stylesheet" href="./demo.css" />
    </head>
    <body>
        <div id="wrapper">
            <form action="" method="post">
                <fieldset>
                    <legend>Advanced search:</legend>
                    <label for="track">Track
                        <input type="text" id="track" name="track" value="<?php echo isset($_POST['track']) ? htmlspecialchars(stripslashes($_POST['track'])) : ''; ?>" />
                    </label>
                    <label for="artist">Artist
                        <input type="text" id="artist" name="artist" value="<?php echo isset($_POST['artist']) ? htmlspecialchars(stripslashes($_POST['artist'])) : ''; ?>" />
                    </label>
                    <label for="album">Album
                        <input type="text" id="artist" name="album" value="<?php echo isset($_POST['album']) ? htmlspecialchars(stripslashes($_POST['album'])) : ''; ?>" />
                    </label>
                    <hr />
                    <p><input type="submit" name="submit" value="Søk" /><input type="hidden" name="checkTime" value="<?php echo time(); ?>" /></p>
                </fieldset>
            </form>





<?php
    // Get the metatune instance. 
    $spotify = MetaTune\MetaTune::getInstance();
    $spotify->autoAddTracksToPlayButton = true; // Will add all searches for tracks into a list.
    $spotify->playButtonHeight = 330; // For viewing the entire playlist
    $spotify->playButtonTheme = "white"; // Changing theme
    $spotify->playButtonView = "list"; // Changing view
    try
    {
        $tracks = array(
            $spotify->lookup("spotify:track:4kO7mrAPfqIrsKwUOK5BFx"),
            $spotify->lookup("spotify:track:0n49fCjNGsbtNOE6cuWk79"),
            $spotify->lookup("spotify:track:5kQ7CU798Sqm1BWNbYHFMa"),
            $spotify->lookup("spotify:track:57Xjny5yNzAcsxnusKmAfA")
        );

        echo $spotify->getPlayButtonAutoGenerated("My favorites");
    }
    catch (MetaTune\MetaTuneException $ex)
    {
        die("<pre>Error\n" . $ex . "</pre>");
    }
?>

        </div>
    </body>
</html>